name: Rails CI

on: [push, pull_request]

jobs:
  CI-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Start MySql
        run: sudo /etc/init.d/mysql start
      - name: Install bundle
        run: sudo gem install bundler
      - name: Update bundle
        run: sudo gem update bundler
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop -c .rubocop.yml
      - name: Rails best practices
        run: bundle exec rails_best_practices -e "db/schema.rb,db/migrate,vendor,app/models/application_record.rb"
      # - name: Rspec
      #   run: |
      #         cd server
      #         DATABASE_USERNAME=root DATABASE_PASSWORD=root DEVELOPMENT_DATABASE_NAME=server_development TEST_DATABASE_NAME=server_test bundle exec rails db:create
      #         DATABASE_USERNAME=root DATABASE_PASSWORD=root DEVELOPMENT_DATABASE_NAME=server_development TEST_DATABASE_NAME=server_test HOST_EMAIL=noreply@example.com HOST=localhost:3000 MAIL_USER_NAME=05bcc6a3209edc MAIL_PASSWORD=92b511f145e80b MAIL_ADDRESS=smtp.mailtrap.io MAIL_DOMAIN=smtp.mailtrap.io MAIL_PORT=587 bundle exec rspec
